version: '3.7'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    container_name: web
    build: .
    volumes: 
      - .:/app
    ports: 
      - "8000:8000"
    env_file:
      - .env
