# Generated by Django 2.2.2 on 2019-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_num', models.CharField(max_length=128)),
                ('to_num', models.CharField(max_length=128)),
                ('time', models.TimeField()),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.AlterModelOptions(
            name='numbers',
            options={'ordering': ['-arabic']},
        ),
    ]
