# Generated by Django 2.2.2 on 2019-06-25 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190625_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'get_latest_by': ['time'], 'ordering': ['-time']},
        ),
    ]
