# Generated by Django 3.2.12 on 2022-03-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190625_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='from_num',
            new_name='convert_from',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='to_num',
            new_name='convert_to',
        ),
        migrations.RemoveField(
            model_name='history',
            name='time',
        ),
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
